# Generated by Django 4.1 on 2022-09-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='is_active',
        ),
    ]
