# Generated by Django 4.1 on 2022-10-06 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_store', '0003_order_alter_goods_options_alter_goodsgroup_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('id',), 'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
        migrations.AlterModelOptions(
            name='orderfilling',
            options={'ordering': ('id',), 'verbose_name': 'Замовлення-наповнення', 'verbose_name_plural': 'Замовлення-наповнення'},
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.BooleanField(default=True, verbose_name='Рекомендую!')),
                ('description', models.TextField(blank=True, verbose_name='Відгук')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='online_store.goods', verbose_name='Найменування товару')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Відгук про товар',
                'verbose_name_plural': 'Відгуки про товари',
                'ordering': ('id',),
            },
        ),
    ]
