# Generated by Django 4.1 on 2022-10-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0006_alter_goods_is_active_alter_goods_is_hot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сума заказу'),
        ),
        migrations.AddField(
            model_name='orderfilling',
            name='price_selling',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ціна продажу'),
        ),
        migrations.AddField(
            model_name='orderfilling',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сума продажу'),
        ),
    ]
