# Generated by Django 4.1 on 2022-10-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0007_order_total_price_orderfilling_price_selling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачений'),
        ),
    ]
