# Generated by Django 4.1 on 2022-10-12 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_store', '0008_alter_goods_photo_alter_order_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, verbose_name='Кількість')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ціна')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сума')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='online_store.goods', verbose_name='Найменування товару')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Кошик',
                'verbose_name_plural': 'Кошики',
                'ordering': ('user', 'goods'),
            },
        ),
    ]
